@startuml Robodogドメインモデル図
skinparam componentStyle rectangle

' Robodog
[ユーザ] o-- [ユーザID]
[ユーザ] o-- [パスワード]
[ユーザ] o-- [名前]
[ユーザ] o-- [学校名]
[ユーザ] o-- [所属名]
[ユーザ] o-- [メールアドレス]
[ユーザ] o-- [電話番号]
[ユーザ] o-- [年齢]

[ログイン情報] o-- [セッショントークン]
[ログイン情報] o-- [リフレッシュトークン]

@enduml