@startuml Web訪問者システム-登録シーケンス図
hide footbox
skinparam boundaryBackgroundColor #D5E8D4
skinparam controlBackgroundColor  #F8CECC
skinparam entityBackgroundColor   #DAE8FC

actor ユーザー as A
boundary 訪問者システムメニュー画面 as B1
boundary 訪問者一覧画面 as B2
control 訪問者一覧表示 as C1
entity 訪問者オブジェクト as E

A -> B1: 「訪問者情報一覧」を選択()
activate B1

B1 -> C1: 起動()
deactivate B1
activate C1
C1 -> E: 情報取得()
deactivate C1
activate E

opt 情報の有無でエラー発生
    C1 -> B2: エラーメッセージ表示()
end

E --> C1:
deactivate E
activate C1
C1 -> B2: 訪問者一覧表示()
deactivate B1
activate B2


@enduml