@startuml 
left to right direction
actor ユーザー as U1
actor システム管理者 as Admin
actor 注文管理者 as Admin2
actor CS as Admin3
actor 倉庫担当者 as Admin4

rectangle ユーザー {
  usecase "アカウント登録する" as UC1
  usecase "アカウント参照する" as UC2
  usecase "アカウント更新する" as UC3
  usecase "アカウント削除する" as UC4
  usecase "ログイン" as UC5
  usecase "ログアウト" as UC6
  usecase "カートに商品を追加する" as UC7
  usecase "カートの商品を削除する" as UC8
  usecase "数量を変更する" as UC9
  usecase "カートを参照する" as UC10
  usecase "カートを更新する" as UC11
  usecase "小計を計算する" as UC12
  usecase "決済履歴を参照する" as UC13
  usecase "商品情報を参照する" as UC14
  usecase "注文を作成する" as UC15
  usecase "注文を参照する" as UC16
  usecase "注文を更新する" as UC17
  usecase "注文をキャンセルする" as UC18
  usecase "注文詳細を参照する" as UC20
  usecase "発送情報を参照する" as UC21
  usecase "配送状況を参照する" as UC22
  usecase "返品を申請する" as UC23
}

U1 --> UC1
U1 --> UC2
U1 --> UC3
U1 --> UC4
U1 --> UC5
U1 --> UC6
U1 --> UC7
U1 --> UC8
U1 --> UC9
U1 --> UC10
U1 --> UC11
U1 --> UC12
U1 --> UC13
U1 --> UC14
U1 --> UC15
U1 --> UC16
U1 --> UC17
U1 --> UC18
U1 --> UC20
U1 --> UC21
U1 --> UC22
U1 --> UC23

rectangle システム {
    usecase "アカウント登録する" as UC25
    usecase "アカウント参照する" as UC26
    usecase "アカウント更新する" as UC27
    usecase "アカウント停止する" as UC28

    usecase "決済履歴を参照する" as UC29
    usecase "商品情報を参照する" as UC30
    usecase "商品情報を登録する" as UC31
    usecase "商品情報を更新する" as UC32
    usecase "商品情報を削除する" as UC33
    usecase "在庫を更新する" as UC34
    usecase "注文詳細を参照する" as UC35
    usecase "注文詳細を更新する" as UC36
    
    usecase "返金状況を更新する" as UC38
    usecase "返金を承認する" as UC39
    usecase "返品状況を更新する" as UC41

    usecase "出荷情報を登録" as UC47
    usecase "出荷情報を参照する" as UC37
    usecase "出荷情報を更新" as UC44
    usecase "出荷対象を選択" as UC45
    usecase "発送依頼を送信する" as UC42
}

Admin --> UC25
Admin --> UC26
Admin --> UC27
Admin --> UC28

Admin2 --> UC29
Admin2 --> UC30
Admin2 --> UC31
Admin2 --> UC32
Admin2 --> UC33
Admin2 --> UC34
Admin2 --> UC35
Admin2 --> UC36

Admin3 --> UC38
Admin3 --> UC39
Admin3 --> UC41
Admin3 --> UC35
Admin3 --> UC36

Admin4 --> UC37
Admin4 --> UC42
Admin4 --> UC44
Admin4 --> UC45
Admin4 --> UC47

@enduml